version: '3.4'

services:


  productapi:
    image: ${DOCKER_REGISTRY-}productapi
    build:
      context: .
      dockerfile: ProductApi/Dockerfile

  orderapi:
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: OrderApi/Dockerfile

  
  customersapi:
    image: ${DOCKER_REGISTRY-}customersapi
    build:
      context: .
      dockerfile: CustomersApi/Dockerfile

